# Generated by Django 4.1.7 on 2023-02-20 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('patronymic', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('date_of_employment', models.DateField()),
                ('salary', models.FloatField()),
                ('supervisor_id', models.PositiveBigIntegerField()),
            ],
        ),
    ]
