# Generated by Django 4.1.5 on 2023-02-20 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree_loader', '0002_alter_employee_supervisor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='supervisor_id',
            field=models.PositiveIntegerField(
                choices=[
                    (1, 1),
                    (2, 2),
                    (3, 3),
                    (4, 4),
                    (5, 5),
                    (6, 6),
                    (7, 7),
                    (8, 8),
                    (9, 9),
                    (10, 10),
                ]
            ),
        ),
    ]
