# Generated by Django 4.1.5 on 2023-02-20 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree_loader', '0003_alter_employee_supervisor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='supervisor_id',
            field=models.PositiveIntegerField(),
        ),
    ]
